Add build-ca-with-key command
build-ca-with-key is similar to build-ca in that it generates a self-signed
ca.crt, but uses an existing ca.key that was manually installed into
$EASYRSA_PKI/private/ca.key.

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -479,6 +479,69 @@ $out_file
 	return 0
 } # => build_ca()
 
+# build-ca-with-key backend:
+build_ca_with_key() {
+	local opts= sub_ca=
+	while [ -n "$1" ]; do
+		case "$1" in
+			nopass) opts="$opts -nodes" ;;
+			subca) sub_ca=1 ;;
+			*) warn "Ignoring unknown command option: '$1'" ;;
+		esac
+		shift
+	done
+
+	verify_pki_init
+
+	# setup for the simpler sub-CA situation and overwrite with root-CA if needed:
+	local out_file="$EASYRSA_PKI/reqs/ca.req"
+	local out_key="$EASYRSA_PKI/private/ca.key"
+	if [ ! $sub_ca ]; then
+		out_file="$EASYRSA_PKI/ca.crt"
+		opts="$opts -x509 -days $EASYRSA_CA_EXPIRE"
+	fi
+
+	# Do not test for existing CA.
+	# Instead, test that a key exists.
+	if [ ! -f "$out_key" ]; then
+		die "\
+Refusing to continue rebuilding CA with a key because no key exists."
+	fi
+
+	# create necessary files and dirs:
+	local err_file="Unable to create necessary PKI files (permissions?)"
+	for i in issued certs_by_serial; do
+		mkdir -p "$EASYRSA_PKI/$i" || die "$err_file"
+	done
+	printf "" > "$EASYRSA_PKI/index.txt" || die "$err_file"
+	print "01" > "$EASYRSA_PKI/serial" || die "$err_file"
+
+	# Default CN only when not in global EASYRSA_BATCH mode:
+	[ $EASYRSA_BATCH ] && opts="$opts -batch" || export EASYRSA_REQ_CN="Easy-RSA CA"
+
+	out_file_tmp="$(mktemp -u "$out_file.XXXXXXXXXX")"; EASYRSA_TEMP_FILE_3="$out_file_tmp"
+	# create a signed CA certificate with the existing CA keypair:
+	"$EASYRSA_OPENSSL" req -utf8 -new \
+		-config "$EASYRSA_SSL_CONF" -key "$out_key" -out "$out_file_tmp" $opts || \
+		die "Failed to build the CA"
+	mv "$out_file_tmp" "$out_file"; EASYRSA_TEMP_FILE_3=
+
+	# Success messages
+	if [ $sub_ca ]; then
+		notice "\
+NOTE: Your sub-CA request is at $out_file
+and now must be sent to you parent CA for signing. Place your resulting cert
+at $EASYRSA_PKI/ca.crt prior to signing operations.
+"
+	else	notice "\
+CA creation complete and you may now import and sign cert requests.
+Your new CA certificate file for publishing is at:
+$out_file
+"
+	fi
+	return 0
+} # => build_ca_with_key()
+
 # gen-dh backend:
 gen_dh() {
 	verify_pki_init
@@ -1198,6 +1261,9 @@ case "$cmd" in
 		;;
 	build-ca)
 		build_ca "$@"
+		;;
+	build-ca-with-key)
+		build_ca_with_key "$@"
 		;;
 	gen-dh)
 		gen_dh
